// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMSHtPBqfhcHPcdshC_lJ2jOJk97jn1R8',
    appId: '1:665056420156:web:577e327fe776eb41937e39',
    messagingSenderId: '665056420156',
    projectId: 'harapanti',
    authDomain: 'harapanti.firebaseapp.com',
    storageBucket: 'harapanti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeTii7y-N-hB8NLNP0GwxHJbua8u-vO7U',
    appId: '1:665056420156:android:2c38a6aeaf494697937e39',
    messagingSenderId: '665056420156',
    projectId: 'harapanti',
    storageBucket: 'harapanti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1mR9yGkqnXB7_d1gV51RobY4fzmk6ak',
    appId: '1:665056420156:ios:0610829b60a043b1937e39',
    messagingSenderId: '665056420156',
    projectId: 'harapanti',
    storageBucket: 'harapanti.appspot.com',
    iosBundleId: 'com.example.harapanti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD1mR9yGkqnXB7_d1gV51RobY4fzmk6ak',
    appId: '1:665056420156:ios:049e272043b517b0937e39',
    messagingSenderId: '665056420156',
    projectId: 'harapanti',
    storageBucket: 'harapanti.appspot.com',
    iosBundleId: 'com.example.harapanti.RunnerTests',
  );
}
